services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pet
      MYSQL_DATABASE: pet
    ports:
      - "3307:3306"
  redis:
    image: redis:7
    ports:
      - "6379:6379"